---
- hosts : docker_engine
  roles:
    - role: install-docker


- hosts: docker-swarm
  roles:
    - role: ansible-dockerswarm


- hosts: db
  remote_user: root
  become: yes
  vars_files:
    - ./vars.yml
  roles:
    - postgresql

- hosts : stack-deploy
  roles:
    - role: stack-deploy
