---
# Docker Swarm networking setup
docker_swarm_interface: "{{ ansible_default_ipv4['alias'] }}"
# Instead of {{ ansible_default_ipv4['alias'] }} you can set any interface, that is listened by docker engine.
# docker_swarm_interface: "eth1"
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_port: 2377

