---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

# Yum install package
- name: Install common packages
  yum: pkg={{item}} state=installed
  with_items :
    - git
    - nano
    - wget
- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  when: docker_restart_on_package_change

# configure docker deamon json file
- name: configure docker daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0400
    owner: root
  notify: restart docker

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users

# stop firewalld 
#- name: "Stop Firewalld service"
#  service:
#    name: firewalld
#    state: stopped
